### ISSUE TITLE
请问怎么回事

### ISSUE THREAD

**Issue by sunnyhmz7010** [clover1420/AutoSign#14]
Traceback (most recent call last):
  File "/workspace/PythonProject/AutoSign-main/main.py", line 4, in <module>
    from steat import push,SignToken
ModuleNotFoundError: No module named 'steat'

执行了 pip install -r requirements.txt 安装模块，运行index.py就提示以上内容

**Comment by clover1420** [comment]
重新拉取一下代码就好了。

**Comment by sunnyhmz7010** [comment]
填入好游快爆cookie，无法继续运行


WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[2023-04-27 16:09:55,153][INFO]:MIUI历史版本:账号或密码为空
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/AutoSign/index.py", line 13, in <module>
    run()
  File "/workspace/AutoSign/main.py", line 19, in run
    data += "\n\n好游快爆:\n"+ body.Sign()
  File "/workspace/AutoSign/src/hykb.py", line 26, in Sign
    zz = requests.post(url=self.Url,data=self.gtfed,headers=self.head).json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by clover1420** [comment]
我晚点看一下。

**Comment by clover1420** [comment]
看看是不是cookie错了。

**Comment by sunnyhmz7010** [comment]
![Screenshot_20230428_124515.jpg](https://user-images.githubusercontent.com/52040067/235056383-492073b3-9758-4b98-a5b8-1bc091a32143.jpg)

是这个吧？

**Comment by clover1420** [comment]
抓一次签到，看这给链接 https://huodong3.3839.com/n/hykb/grow/ajax.php 看请求里面的text

**Comment by clover1420** [comment]
![QQ图片20230428125431](https://user-images.githubusercontent.com/47273274/235057702-3449ccd6-dd95-4f4f-9b98-895fe07d0d09.jpg)

**Comment by sunnyhmz7010** [comment]
噢好的，就是要把scookie=后面的内容填进去是吧

**Comment by clover1420** [comment]
全部填进去就行了

**Comment by sunnyhmz7010** [comment]
> 全部填进去就行了

好勒，非常感谢
